# Generated by Django 6.0.4 on 2026-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
