# Generated by Django 6.0.4 on 2026-04-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='name',
            new_name='expense_name',
        ),
    ]
