# Generated by Django 6.0.4 on 2026-04-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_income_income_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecategory',
            old_name='income_name',
            new_name='income_category',
        ),
    ]
