# Generated by Django 6.0.4 on 2026-04-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_expensecategory_expense_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='expense_name',
            new_name='expense_category',
        ),
    ]
