# Generated by Django 6.0.4 on 2026-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_categoryrule_expensecategoryrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_nickname',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
    ]
