# Generated by Django 6.0.4 on 2026-04-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='liability',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
    ]
