# Generated by Django 6.0.4 on 2026-04-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_asset_account_liability_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_amount',
        ),
    ]
