# Generated by Django 6.0.4 on 2026-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_asset_asset_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
