# Generated by Django 6.0.4 on 2026-04-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_asset_asset_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
