# Generated by Django 6.0.4 on 2026-05-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_account_plaid_account_id_plaiditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
