# Generated by Django 6.0.4 on 2026-05-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transaction_plaid_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='cursor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
